# Generated by Django 5.1.6 on 2025-04-12 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerant_dashboard', '0001_initial'),
        ('pdg_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenudish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdg_dashboard.dish'),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='dishes',
            field=models.ManyToManyField(through='gerant_dashboard.DailyMenuDish', to='pdg_dashboard.dish'),
        ),
        migrations.AddField(
            model_name='specialclient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='table',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='pdg_dashboard.store'),
        ),
        migrations.AddField(
            model_name='reservationhistory',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerant_dashboard.table'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gerant_dashboard.table'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymenudish',
            unique_together={('daily_menu', 'dish')},
        ),
    ]
