# Generated by Django 5.1.6 on 2025-04-12 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerant_dashboard', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenu',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
