# Generated by Django 5.1.7 on 2025-03-29 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerant_dashboard', '0002_alter_reservation_client_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='reservationhistory',
            name='client_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('not_reserved', 'Not Reserved')], default='reserved', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerant_dashboard.table'),
        ),
    ]
