# Generated by Django 5.1.7 on 2025-04-13 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerant_dashboard', '0003_remove_dailymenu_created_by_alter_dailymenu_date'),
        ('pdg_dashboard', '0005_delete_menuitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'gerant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='pdg_dashboard.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='dailymenu',
            unique_together={('date', 'store')},
        ),
    ]
