# Generated by Django 5.1.7 on 2025-03-29 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerant_dashboard', '0003_alter_reservationhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationhistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('not_reserved', 'Not Reserved')], default='not_reserved', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gerant_dashboard.table'),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='client_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerant_dashboard.table'),
        ),
    ]
