# Generated by Django 5.1.7 on 2025-04-13 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerant_dashboard', '0004_dailymenu_created_by_dailymenu_store_and_more'),
        ('pdg_dashboard', '0006_remove_order_table_alter_order_created_at_orderdish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDishForOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdg_dashboard.dish')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdg_dashboard.store')),
            ],
            options={
                'unique_together': {('store', 'dish', 'date')},
            },
        ),
    ]
