# Generated by Django 5.1.7 on 2025-03-29 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerant_dashboard', '0004_alter_reservationhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationhistory',
            name='moved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservationhistory',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('canceled', 'Canceled')], max_length=20),
        ),
    ]
