# Generated by Django 5.1.7 on 2025-04-13 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerant_dashboard', '0005_availabledishfororder'),
        ('pdg_dashboard', '0006_remove_order_table_alter_order_created_at_orderdish_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'chef'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MenuOfToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('generated_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_of_today', to='gerant_dashboard.dailymenu')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus_of_today', to='pdg_dashboard.store')),
            ],
            options={
                'unique_together': {('date', 'store')},
            },
        ),
        migrations.CreateModel(
            name='MenuOfTodayDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.PositiveIntegerField()),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdg_dashboard.dish')),
                ('menu_of_today', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='gerant_dashboard.menuoftoday')),
            ],
            options={
                'unique_together': {('menu_of_today', 'dish')},
            },
        ),
        migrations.DeleteModel(
            name='AvailableDishForOrder',
        ),
    ]
