# Generated by Django 5.1.7 on 2025-04-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerant_dashboard', '0007_specialclient_delete_clientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialclient',
            name='type',
            field=models.CharField(choices=[('fidele', 'Client fidèle'), ('enterprise', 'Entreprise')], default='simple', max_length=20),
        ),
    ]
