# Generated by Django 5.1.7 on 2025-04-13 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerant_dashboard', '0008_remove_reservation_client_name_reservation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='client',
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationhistory',
            name='client_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
