# Generated by Django 5.1.7 on 2025-03-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdg_dashboard', '0003_category_alter_menuitem_category_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='store',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_photos/'),
        ),
    ]
