# Generated by Django 5.1.6 on 2025-04-12 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdg_dashboard', '0003_alter_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='pdg_dashboard.category'),
            preserve_default=False,
        ),
    ]
