# Generated by Django 5.1.6 on 2025-04-13 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdg_dashboard', '0004_alter_dish_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'fournisseur'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_needed', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdg_dashboard.ingredient')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdg_dashboard.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='ingredients',
            field=models.ManyToManyField(through='pdg_dashboard.SupplierIngredient', to='pdg_dashboard.ingredient'),
        ),
        migrations.CreateModel(
            name='SupplierIngredientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.FloatField()),
                ('date_requested', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('delivered', 'Livrée')], default='pending', max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdg_dashboard.ingredient')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdg_dashboard.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdg_dashboard.supplier')),
            ],
        ),

    ]
