# Generated by Django 5.1.7 on 2025-04-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdg_dashboard', '0004_alter_dish_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
