# Generated by Django 5.1.6 on 2025-04-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdg_dashboard', '0005_supplier_supplieringredient_supplier_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieringredient',
            name='quantity_needed',
        ),

    ]
