# Generated by Django 5.1.7 on 2025-04-11 11:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdg_dashboard', '0005_order_notes_order_table_order_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('encaissement', 'Encaissement'), ('decaissement', 'Décaissement')], max_length=20)),
                ('category', models.CharField(choices=[('facture', 'Facture'), ('salaire', 'Salaire'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Payé'), ('unpaid', 'Non Payé'), ('canceled', 'Annulé')], default='paid', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pdg_dashboard.store')),
            ],
        ),
    ]
