# Generated by Django 5.1.6 on 2025-04-14 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdg_dashboard', '0006_remove_supplieringredient_quantity_needed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('date_responded', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdg_dashboard.supplieringredientrequest')),
            ],
        ),

    ]
