# Generated by Django 5.1.7 on 2025-04-13 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerant_dashboard', '0006_alter_dailymenu_created_by_menuoftoday_and_more'),
        ('pdg_dashboard', '0007_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine-in'), ('takeaway', 'Takeaway')], default='dine_in', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerant_dashboard.table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdg_dashboard.store'),
        ),
    ]
